const std = @import("std");
const toml = @import("toml.zig"); // wired via the cargo module; see build.zig note in Plan C Task 5

pub const LockError = error{ InvalidLock, ParseError, UnsupportedType, OutOfMemory };
pub const LockPackage = struct {
    name: []const u8,
    version: []const u8,
    source: ?[]const u8, // "registry+https://…" | "git+https://…#rev" | null for path deps
    checksum: ?[]const u8, // sha256 hex; opaque passthrough (verified in M2)
    dependencies: []const []const u8, // edge list as written ("name version (source)" short form supported)
};
pub const Lockfile = struct {
    arena: std.heap.ArenaAllocator, // owns ALL borrowed strings/slices below; deinit frees it
    version: u32, // `version = 4` header; default 3 when absent
    packages: []LockPackage,
    pub fn deinit(self: *Lockfile) void {
        self.arena.deinit();
    }
    pub fn find(self: *const Lockfile, name: []const u8) ?LockPackage {
        for (self.packages) |p| {
            if (std.mem.eql(u8, p.name, name)) return p;
        }
        return null;
    }
    pub fn serialize(self: *const Lockfile, gpa: std.mem.Allocator) LockError![]u8 {
        // Byte-stable cargo v4 emission: fixed header, `version = N`, then
        // per-package blocks in slice order with fields in cargo's order
        // (name, version, source?, checksum?, dependencies? multi-line array
        // with one-space indent and trailing commas exactly as cargo writes).
        var out: std.ArrayList(u8) = .empty;
        errdefer out.deinit(gpa);
        try out.appendSlice(gpa, "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = ");
        var numbuf: [10]u8 = undefined;
        try out.appendSlice(gpa, std.fmt.bufPrint(&numbuf, "{d}", .{self.version}) catch return LockError.OutOfMemory);
        try out.appendSlice(gpa, "\n");
        for (self.packages) |pkg| {
            try out.appendSlice(gpa, "\n[[package]]\nname = \"");
            try appendEscaped(&out, gpa, pkg.name);
            try out.appendSlice(gpa, "\"\nversion = \"");
            try appendEscaped(&out, gpa, pkg.version);
            try out.appendSlice(gpa, "\"\n");
            if (pkg.source) |s| {
                try out.appendSlice(gpa, "source = \"");
                try appendEscaped(&out, gpa, s);
                try out.appendSlice(gpa, "\"\n");
            }
            if (pkg.checksum) |c| {
                try out.appendSlice(gpa, "checksum = \"");
                try appendEscaped(&out, gpa, c);
                try out.appendSlice(gpa, "\"\n");
            }
            if (pkg.dependencies.len > 0) {
                try out.appendSlice(gpa, "dependencies = [\n");
                for (pkg.dependencies) |dep| {
                    try out.appendSlice(gpa, " \"");
                    try appendEscaped(&out, gpa, dep);
                    try out.appendSlice(gpa, "\",\n");
                }
                try out.appendSlice(gpa, "]\n");
            }
        }
        return try out.toOwnedSlice(gpa);
    }
};

/// TOML basic-string escaping for the serializer. Real lockfiles never
/// contain characters needing escapes in these positions (names, versions,
/// URLs, hex checksums, dep edges), so this is a no-op on real cargo output
/// and only fires on adversarial input, where verbatim emission would corrupt
/// the round-trip the parser's escape decoding promises.
fn appendEscaped(out: *std.ArrayList(u8), gpa: std.mem.Allocator, s: []const u8) LockError!void {
    for (s) |c| {
        switch (c) {
            '"' => try out.appendSlice(gpa, "\\\""),
            '\\' => try out.appendSlice(gpa, "\\\\"),
            '\n' => try out.appendSlice(gpa, "\\n"),
            '\r' => try out.appendSlice(gpa, "\\r"),
            '\t' => try out.appendSlice(gpa, "\\t"),
            0x00...0x08, 0x0B, 0x0C, 0x0E...0x1F, 0x7F => {
                var buf: [6]u8 = undefined;
                const esc = std.fmt.bufPrint(&buf, "\\u{X:0>4}", .{c}) catch return LockError.OutOfMemory;
                try out.appendSlice(gpa, esc);
            },
            else => try out.append(gpa, c),
        }
    }
}

pub fn parseLock(gpa: std.mem.Allocator, text: []const u8) LockError!Lockfile {
    const doc = toml.parseDocument(gpa, text) catch |e| return switch (e) {
        toml.TomlError.ParseError => LockError.ParseError,
        toml.TomlError.UnsupportedType => LockError.UnsupportedType,
        toml.TomlError.OutOfMemory => LockError.OutOfMemory,
    };
    // NOTE: doc.arena outlives the Lockfile — Lockfile borrows strings from it.
    // Ownership transfer (exact): move doc.arena into the returned Lockfile; Lockfile.deinit frees it.
    // `doc` itself is never deinitialized; only the moved arena is.
    var lf = Lockfile{ .arena = doc.arena, .version = 3, .packages = &.{} };
    // Every fallible step below allocates from the arena only, so freeing the
    // arena covers all error paths (same shape as Manifest's errdefer).
    errdefer lf.arena.deinit();
    const alloc = lf.arena.allocator();
    if (doc.root.get("version")) |vv| {
        if (vv.* != .integer or vv.integer < 0) return LockError.InvalidLock;
        lf.version = std.math.cast(u32, vv.integer) orelse return LockError.InvalidLock;
    }
    if (doc.root.get("package")) |pv| {
        if (pv.* != .array) return LockError.InvalidLock;
        var pkgs: std.ArrayList(LockPackage) = .empty;
        for (pv.array) |*entry| {
            if (entry.* != .table) return LockError.InvalidLock;
            try pkgs.append(alloc, try parsePackage(alloc, &entry.table));
        }
        lf.packages = try pkgs.toOwnedSlice(alloc);
    }
    return lf;
}

fn parsePackage(alloc: std.mem.Allocator, t: *const toml.TomlTable) LockError!LockPackage {
    const name = try requiredField(t, "name");
    const version = try requiredField(t, "version");
    // Unknown keys are ignored (forward-compat across lock versions); the
    // serializer only emits the five known fields.
    return .{
        .name = name,
        .version = version,
        .source = try optionalField(t, "source"),
        .checksum = try optionalField(t, "checksum"),
        .dependencies = try parseEdges(alloc, t),
    };
}

fn requiredField(t: *const toml.TomlTable, key: []const u8) LockError![]const u8 {
    const v = t.get(key) orelse return LockError.InvalidLock;
    if (v.* != .string) return LockError.InvalidLock;
    return v.string;
}

fn optionalField(t: *const toml.TomlTable, key: []const u8) LockError!?[]const u8 {
    const v = t.get(key) orelse return null;
    if (v.* != .string) return LockError.InvalidLock;
    return v.string;
}

/// Dependency edges are kept verbatim as written, including cargo's
/// `"name version (source)"` disambiguation form — opaque strings in,
/// opaque strings out. Absent `dependencies` means no edges (cargo omits the
/// key rather than writing an empty array).
fn parseEdges(alloc: std.mem.Allocator, t: *const toml.TomlTable) LockError![]const []const u8 {
    const v = t.get("dependencies") orelse return &.{};
    if (v.* != .array) return LockError.InvalidLock;
    // Edge strings borrow the doc arena; only the slice header is allocated.
    const out = try alloc.alloc([]const u8, v.array.len);
    for (v.array, out) |*item, *slot| {
        if (item.* != .string) return LockError.InvalidLock;
        slot.* = item.string;
    }
    return out;
}

fn readFixture(path: []const u8) ![]u8 {
    // Runtime read (not @embedFile): the plan's snippet embeds
    // "../../testdata/…", but that escapes the module package path, so it
    // cannot compile under standalone `zig test src/cargo/lock.zig`.
    // Repo-root-relative reads match the plan's own Task 4 test convention
    // (tests run with cwd = repo root).
    const io = std.Io.Threaded.global_single_threaded.io();
    return try std.Io.Dir.cwd().readFileAlloc(io, path, std.testing.allocator, .limited(1 << 20));
}

test "lock parses v4 fixture and round-trips" {
    const text = try readFixture("testdata/cargo/minimal/Cargo.lock");
    defer std.testing.allocator.free(text);
    var lf = try parseLock(std.testing.allocator, text);
    defer lf.deinit();
    try std.testing.expectEqual(@as(u32, 4), lf.version);
    const serde = lf.find("serde").?;
    try std.testing.expectEqualStrings("1.0.200", serde.version);
    try std.testing.expect(serde.checksum != null);
    const out = try lf.serialize(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings(text, out);
}

test "lock rejects package without version" {
    try std.testing.expectError(LockError.InvalidLock, parseLock(std.testing.allocator, "[[package]]\nname = \"x\"\n"));
}

test "lock defaults to version 3 when the header is absent" {
    var lf = try parseLock(std.testing.allocator, "[[package]]\nname = \"x\"\nversion = \"0.1.0\"\n");
    defer lf.deinit();
    try std.testing.expectEqual(@as(u32, 3), lf.version);
    try std.testing.expectEqual(@as(usize, 1), lf.packages.len);
    try std.testing.expect(lf.find("missing") == null);
}

test "lock keeps disambiguated edges verbatim" {
    const text =
        \\# This file is automatically @generated by Cargo.
        \\# It is not intended for manual editing.
        \\version = 4
        \\
        \\[[package]]
        \\name = "app"
        \\version = "0.1.0"
        \\dependencies = [
        \\ "foo 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
        \\ "foo 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
        \\]
        \\
        \\[[package]]
        \\name = "foo"
        \\version = "1.0.0"
        \\source = "registry+https://github.com/rust-lang/crates.io-index"
        \\checksum = "aaaa"
        \\
        \\[[package]]
        \\name = "foo"
        \\version = "2.0.0"
        \\source = "registry+https://github.com/rust-lang/crates.io-index"
        \\checksum = "bbbb"
        \\
    ;
    var lf = try parseLock(std.testing.allocator, text);
    defer lf.deinit();
    const app = lf.find("app").?;
    try std.testing.expectEqual(@as(usize, 2), app.dependencies.len);
    try std.testing.expectEqualStrings("foo 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)", app.dependencies[0]);
    const out = try lf.serialize(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings(text, out);
}

test "lock round-trips real cargo output byte-identically" {
    // Oracle: these goldens are real `cargo generate-lockfile` bytes
    // (committed alongside the validation corpus; `validation/oracle.sh`
    // regenerates them from the real cargo binary). They cover path-only
    // packages (no source/checksum/dependencies keys), multi-entry edge
    // lists, and registry packages with checksums.
    const paths = [_][]const u8{
        "validation/basic-workspace/Cargo.lock",
        "validation/lockfile-golden/Cargo.lock",
    };
    for (paths) |path| {
        const text = try readFixture(path);
        defer std.testing.allocator.free(text);
        var lf = try parseLock(std.testing.allocator, text);
        defer lf.deinit();
        try std.testing.expectEqual(@as(u32, 4), lf.version);
        try std.testing.expect(lf.packages.len > 0);
        const out = try lf.serialize(std.testing.allocator);
        defer std.testing.allocator.free(out);
        try std.testing.expectEqualStrings(text, out);
    }
}

test "lock oracle fixtures have the expected shape" {
    const text = try readFixture("validation/basic-workspace/Cargo.lock");
    defer std.testing.allocator.free(text);
    var lf = try parseLock(std.testing.allocator, text);
    defer lf.deinit();
    try std.testing.expectEqual(@as(usize, 15), lf.packages.len);
    // Path-only workspace member: no source, no checksum, has edges.
    const cli = lf.find("cli-bin").?;
    try std.testing.expect(cli.source == null);
    try std.testing.expect(cli.checksum == null);
    try std.testing.expectEqual(@as(usize, 4), cli.dependencies.len);
    // Registry package: source + checksum present, edges verbatim.
    const serde = lf.find("serde").?;
    try std.testing.expectEqualStrings("registry+https://github.com/rust-lang/crates.io-index", serde.source.?);
    try std.testing.expect(serde.checksum != null);
    try std.testing.expectEqualStrings("serde_core", serde.dependencies[0]);
    try std.testing.expectEqualStrings("serde_derive", serde.dependencies[1]);
    // Leaf package: keys omitted entirely, not empty.
    const anyhow = lf.find("anyhow").?;
    try std.testing.expectEqual(@as(usize, 0), anyhow.dependencies.len);
}
